### PR TITLE
Add implementation of basic model diagnostic plots

### PR DESCRIPTION
**Pull request by rrebane**
* The `plot_trace` function mimics the `arviz` function with the same name in basic functions but is implemented with `altair`.
* Add separate `streamlit` tool.
* Add basic documentation.
* Add example trace file.

### CODE REVIEW

**Comment by rrebane** [comment]
Updated the PR.

* The aggregation for the density plot is no longer done by `altair` and is now manually aggregated beforehand.
* Replaced the trace plot with a "trace rank" plot to reduce the amount of data that `altair` needs to handle while giving similar information.
* Category name aggregation is still done with `altair`.
* Attempted to improve the general structure of the code.

Screenshot from the `streamlit` app:

Screenshot 2024-07-02 222515

**Comment by rrebane** [comment]
Updated [`321f5f1` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/321f5f1d6d2f6c111750de6e19b53d33135dfd74).

* Renamed `trace_rank` to `rank`.
* Added Sturges' formula for calculating the number of bins for the `rank` plot.
* Added uniform reference line to the `rank` plot.

Note. Also tried to show the ranks as a step chart (see below) but for me it was less readable than the line chart.

Screenshot 2024-07-04 133634

**Comment by rrebane** [comment]
Updated [`483f948` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/483f94813d1bf3082042cb8cd6404464191c1de4).

* Decided to go with the step chart (i.e. the screenshot above).
* Normalized the rank plot bin values.
* Rank graph y axis now always includes 0.
* Divided density plot y axis values by 100. I assume that `scipy.stats.gaussian_kde` `evaluate` returns percentages.

**Comment by rrebane** [comment]
Updated.

* Fixed some minor issues in [`bd04511` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/bd04511820e747cf60e945ceab2af5867069dc9f) and [`8cfa9e0` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/8cfa9e0f071b3585aec652fc42ea988e56d7ca9f).
* Added support for showing heatmaps of variable dimensions in [`69f150c` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/69f150c62860eb5630740dffcc0a6cd35bd576d6).
* Updated "heatmap" plot type support to `btracer` Streamlit tool in [`d4614ea` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/d4614ea87d54089d0983b7458323c43bb88d2056).

The screenshot below shows what the heatmap looks like.

image

**Comment by rrebane** [comment]
Updated.

* Added `plot_correlation` function in [`0efe89b` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/0efe89bd031b41340a9c97b74b13d313885ca6f5).

The correlation plots in `btracer` Streamlit look something like this:
Screenshot 2024-07-08 154453

**Comment by velochy** [comment]
Downloaded your branch and tried it out. Looks pretty good. 

Nevertheless, some notes:
* I would simplify the file selctor to just look for .nc files in the same folder streamlit is called in, and allow passing either a directory or file path in a cmd line parameter. The current two tier structure, while it makes sense for my projects, does not generalize well overall imho. 
* It should never show an empty page. When no graph is to be displayed, it should say why not. Found myself waiting for godot a few times that way
* Something is off w correllation plots:
image
What I expected as output was tables of gender x party (like I got), but one per party, not one per party-gender combo..

**Comment by rrebane** [comment]
Updated with [`35b8b53` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/35b8b53efb0831cbc6256aab6a57e2147364db27) and [`f65396e` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/f65396ee2cb3cfdc6f91ed6b27b05ba9cbcef843).

* Improved command line path handling.
* Now shows messages when input is expected from user.
* ~~I think I fixed the issue with correlation plot. However, I am not 100% sure I understand how it should behave in all situations.~~
	* Might be working correctly now with [`e02e415` (#1)](https://github.com/salk-ee/btracer/pull/1/commits/e02e415964f0bdd88430e3a519e92fa4cac9706b).

**Comment by rrebane** [comment]
Squashed and re-organized the commits so that the commit history would be more readable. I think this PR can be merged in this state, assuming you don't see any problems with the implemented functionality.

**Pull request merged**
